# Generated by Django 4.2.6 on 2023-10-21 21:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adopcion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('fecha_adopcion', models.DateField()),
                ('comentarios', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoAdopcion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('estado', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('raza', models.CharField(max_length=50)),
                ('edad', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('disponible', models.BooleanField(default=True)),
                ('color', models.CharField(max_length=50)),
                ('tamano', models.CharField(max_length=20)),
                ('genero', models.CharField(choices=[('macho', 'Macho'), ('hembra', 'Hembra')], max_length=10)),
                ('likes', models.IntegerField(default=0)),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.especie')),
                ('etiquetas', models.ManyToManyField(to='api.etiqueta')),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15)),
                ('dni', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('fecha_nacimiento', models.DateField()),
                ('genero', models.CharField(choices=[('masculino', 'Masculino'), ('femenino', 'Femenino'), ('otro', 'Otro')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Vacuna',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nombre_vacuna', models.CharField(max_length=100)),
                ('fecha_administracion', models.DateField()),
                ('proxima_fecha_vacunacion', models.DateField()),
                ('notas_adicionales', models.TextField()),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.mascota')),
            ],
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('imagen', models.ImageField(upload_to='imagenes_mascotas/')),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.mascota')),
            ],
        ),
        migrations.CreateModel(
            name='EvaluacionAdopcion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('calificacion', models.PositiveIntegerField()),
                ('comentarios', models.TextField()),
                ('fecha_evaluacion', models.DateField()),
                ('adopcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.adopcion')),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('direccion', models.TextField()),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.persona')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('contenido', models.TextField()),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.persona')),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.mascota')),
            ],
        ),
        migrations.AddField(
            model_name='adopcion',
            name='estado_adopcion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.estadoadopcion'),
        ),
        migrations.AddField(
            model_name='adopcion',
            name='mascota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.mascota'),
        ),
        migrations.AddField(
            model_name='adopcion',
            name='usuario_administrador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adopciones_gestionadas', to='api.persona'),
        ),
        migrations.AddField(
            model_name='adopcion',
            name='usuario_adoptante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adopciones_realizadas', to='api.persona'),
        ),
    ]
