# Generated by Django 4.2.6 on 2023-10-26 03:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_visitaadopcion_asistio"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="persona",
            name="genero",
        ),
    ]
