# Generated by Django 4.2.6 on 2023-10-26 04:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_remove_persona_genero"),
    ]

    operations = [
        migrations.AddField(
            model_name="especie",
            name="imagen",
            field=models.ImageField(null=True, upload_to="imagenes_mascotas/"),
        ),
    ]
