# Generated by Django 4.2.6 on 2023-10-26 05:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_especie_imagen"),
    ]

    operations = [
        migrations.CreateModel(
            name="Evento",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("nombre", models.CharField(max_length=300)),
                ("fecha_inicio", models.DateField()),
                ("fecha_fin_participacion", models.DateField()),
                (
                    "costo_participacion",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("recaudacion", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name="adopcion",
            name="usuario_administrador",
        ),
        migrations.AlterField(
            model_name="visitaadopcion",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.CreateModel(
            name="VisitaGeneral",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("fecha_visita", models.DateField()),
                ("asistio", models.BooleanField(default=False, null=True)),
                (
                    "persona",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.persona"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventoParticipante",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "evento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.evento"
                    ),
                ),
                (
                    "participante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.persona"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Donacion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("descripcion", models.TextField()),
                ("fecha_donacion", models.DateField()),
                (
                    "persona",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.persona"
                    ),
                ),
            ],
        ),
    ]
