# Generated by Django 4.2.6 on 2023-10-26 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0009_evento_remove_adopcion_usuario_administrador_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventoparticipante",
            name="ticket",
            field=models.PositiveIntegerField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="evento",
            name="recaudacion",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name="Premio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("descripcion", models.TextField()),
                (
                    "evento",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.evento",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ganador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "evento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.evento"
                    ),
                ),
                (
                    "participante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.eventoparticipante",
                    ),
                ),
                (
                    "premio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.premio"
                    ),
                ),
            ],
        ),
    ]
