# Generated by Django 4.2.6 on 2023-10-27 06:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0011_alter_adopcion_fecha_adopcion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventoparticipante",
            name="ticket",
            field=models.PositiveIntegerField(null=True, unique=True),
        ),
    ]
