# Generated by Django 4.2.6 on 2023-10-27 06:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0012_alter_eventoparticipante_ticket"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventoparticipante",
            name="ticket",
            field=models.PositiveIntegerField(default=1, editable=False, unique=True),
            preserve_default=False,
        ),
    ]
