# Generated by Django 4.2.6 on 2023-10-29 00:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0013_alter_eventoparticipante_ticket"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="evaluacionadopcion",
            name="adopcion",
        ),
        migrations.RemoveField(
            model_name="visitaadopcion",
            name="adoptante",
        ),
        migrations.RemoveField(
            model_name="visitaadopcion",
            name="mascota",
        ),
        migrations.RemoveField(
            model_name="visitageneral",
            name="persona",
        ),
        migrations.AddField(
            model_name="adopcion",
            name="fecha_visita",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="evento",
            name="finalizo",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="evento",
            name="tiene_premio",
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name="Donacion",
        ),
        migrations.DeleteModel(
            name="EvaluacionAdopcion",
        ),
        migrations.DeleteModel(
            name="VisitaAdopcion",
        ),
        migrations.DeleteModel(
            name="VisitaGeneral",
        ),
    ]
