# Generated by Django 4.2.6 on 2023-10-29 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0014_remove_evaluacionadopcion_adopcion_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="evento",
            name="codigo",
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="ganador",
            name="participante",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.eventoparticipante",
            ),
        ),
    ]
